export const sentences = [
  'Counting my calories',
  'He told us an adventure story',
  'Don’t step on the broken glass',
  'Come back tomorrow if you can',
  'I need more detailed information',
  'There is a reason that roses have thorns',
  'She was hiding behind the curtain',
  'It’s not brain surgery',
  'Be careful with that butter knife',
  'Wait outside of the house',
  'A slippery slope',
  'She folded her handkerchief neatly',
  'A glittering gem is not enough',
  'I caught a squirrel rustling through my bag',
  'His seven-layer cake only has six layers',
  'All you need to do is pick up the pen',
  'They ran around the corner to find her',
  'Working two jobs to make ends meet',
  'Nobody loves a pig wearing lipstick',
  'I’d rather be a bird than a fish',
  'Keep your eyes peeled',
  'We cannot afford a vacation',
  'A manifestation of great emotion',
  'Keep a diary',
  'Pomp and circumstance',
  'Beating a dead horse',
  'Indirect sunlight',
  'Moss-grown ideas about life',
  'Play this more allegretto',
  'Went shopping for a reliable plumber',
  'Statute law',
  'The analogical use of a metaphor',
  'The corn is sprouted',
  'Gave advance warning',
  'Stands jam-packed with fans',
  '• We require our secretary to be on time',
  'His stomach bulged after a huge meal',
  'Mystify the story',
  'A wide-open town',
  'Intermittent rain showers',
  'The old man’s scraggly beard',
  'Curvilinear tracery',
  'The surfaces were coarsely granular',
  'They vociferated their demands',
  'A loveless childhood',
  'There is more wine coming',
  'An inconclusive reply',
  'A fevered imagination',
  'Lifelessly he performed the song',
  'He wondered bleakly',
  'Let’s race and see who gets there first',
  'Some sharp and whipping lines',
  'Silver speech',
  'Phrase a musical passage',
  'An unwilling smile',
  'A dreadful storm',
  'Mustard and ketchup are condiments',
  'Rough-dry the laundry',
  'A zany sense of humor',
  'You look simply smashing',
  'First-string players',
  'In naturalistic colors',
  'A spiritless reply to criticism',
  'Felt tongue-tied with embarrassment',
  'Harmless bacteria',
  'Untufted ears',
  'They work hand in glove',
  'We live in a cybernated age',
  'Prompted by malign motives',
  'A barbarous crime',
  'Inducement of sleep',
  "They didn't have to use coercion",
  'Gilt-edged securities',
  'Secondarily affected',
  'A long-distance runner',
  'Syntactically ill-formed',
  'A mechanized factory',
  'Engrave the pen with the owner’s name',
  'Flamboyant handwriting',
  'The disquietingly close sound of gunfire',
  'It was exposed to the air',
  'A large intermixture of sand',
  'She loved him dearly',
  'This gave me the creepy-crawlies',
  'An idyllic spot for a picnic',
  'Another instance occurred yesterday',
  'A pensionable employee',
  'The upper limb of the bow',
  'An account in arrears',
  'Obsolete words',
  'The moon cast soft shadows',
  'Normal vesicular breathing',
  'Doesn’t know when he’s well-off',
  'The curtain swooshed open',
  'He stuck his head in the doorway',
  'Afforest the mountains',
  'This would help a great deal',
  'His augmented renown',
  'Brassbound traditions',
  'The emptiness of outer space',
];
