export const sentences = [
  'They discovered it by accident.',
  'I don’t notice any improvements.',
  'Diagnosed at the age of seven.',
  'I wasn’t fast enough.',
  'I stutter when reading aloud.',
  'Reading everything the same way.',
  'It switched over time.',
  'It is what it is.',
  'I like reading.',
  'It’s kinda like a muscle.',
  'It’s getting better.',
  'Inventing new words.',
  'Nobody really knew it existed.',
  'Professionally is difficult.',
  'Balance is key.',
  'I blink a lot while reading.',
  'It’s very confusing.',
  'Equally bad in my case.',
  'Slower than the average person.',
  'Especially with longer words.',
  'This happens in a millisecond.',
  'This was twice a week.',
  'Anything too bold or thick.',
  'It goes with more ease.',
  'It takes a lot of time.',
  'Broadly speaking it isn’t too bad.',
  'It’s a chain reaction really',
  'Everybody makes mistakes.',
  'It is how things are currently.',
  'Discover how to write words.',
  'It got more easy over time.',
  'More-often than my head.',
  'The term didn’t exist back then.',
  'Improvement isn’t noticeably.',
  'Check for spelling mistakes.',
  'My mind wanders off quickly.',
  'I am often quite late.',
  'Just a larger typesetting.',
  'There’s a big difference.',
  'It’s much easier this way.',
  'Exchange letters in a word.',
  'Jump from one side to another.',
  'It’s just embarrassing.',
  'I learned to live with it.',
  'Luckily I’ve a feel for tongue.',
  'He dropped out of high school.',
  'I have learned to manage it.',
  'I most definitely thought so.',
  'It became an instant fascination.',
  'I really wanted to learn this.',
  'This changed my life forever.',
  'I don’t feel like I’ve improved.',
  'I learned how to play around it.',
  'Accentuated when reading.',
  'Hope this helped.',
  'Issues with reading diphthongs.',
  'They change and rotate easily.',
  'This doesn’t happen every day.',
  'Varies from time to time.',
  'A slight inconvenience.',
  'A combination of several.',
  'The only adult in the waiting room.',
  'The phenomenon was not known.',
  'I tried to make myself smarter.',
  'Creating tricks to perform better.',
  'I quickly lose sight of things.',
  'It hinders punctuality.',
  'I don’t really use crazy typefaces.',
  'Shows a three-dimensional effect.',
  'Not ashamed of having dyslexia.',
  'Without a doubt.',
  'I am a slow reader.',
  'Problems are generally based.',
  'Luckily for autocorrect.',
  'Luckily for spelling checkers.',
  'I cannot read ahead.',
  'Using more neutral typefaces.',
  'The symptoms occur in both.',
  'I have to re-read and adjust.',
  'I will make too many mistakes.',
  'As little as possible.',
  'Reading in front of people.',
  'Reading longer sentences.',
  'Can be frustrating at times.',
  'It can be confronting as well.',
  'Words stick together.',
  'I continually make mistakes.',
  'Mistakes without hearing them.',
  'Challenging myself regularly.',
  'Vowels change place in a word.',
  'Some contradictions are true.',
  'Struggle with reading abilities.',
  'It’s a personal preference.',
  'Everything was new to me.',
  'Sometimes I forget I have it.',
  'Reducing space between letters.',
  'Nevertheless I keep trying.',
  'Neuro developmental condition.',
  'Maintaining reading skills.',
  'Requires much concentration.',
  'Uncertainty will remain forever.',
  'No other disabilities.',
  'Everyone else starts laughing.',
  'We grew up with the internet.',
  'Mistakes aren’t a big deal.',
  'I am reading it incorrectly.',
  'Sometimes I guess wrong.',
  'Recreating the content in a way.',
  'Recognize structures in general.',
  'Kind of typeface has no influence.',
  'It’s not really an issue.',
  'My nephew also struggles with it.',
  'Lines become one block of text.',
  'All the same or quite similar.',
  'I find it more calming.',
  'Difficult to manage everything.',
  'Adapting into using technology.',
  'I don’t read things fluently.',
  'Especially the meaning of it.',
  'Fifty-fifty chance it’s wrong.',
  'I always failed really badly.',
  'Learning by heart.',
  'Take my glasses as they relax.',
  'I guess I am cheating a bit.',
  'Words begin to float.',
  'Going over a word several times.',
  'I quickly doubt myself.',
  'With perseverance I manage.',
  'I tend to lose the sequence.',
  'They are more recognizable.',
  'Reading things double.',
  'Keeping myself calm.',
  'Light or very bold typefaces.',
  'Close or very wide lining.',
  'Tight or very large spacing.',
  'Hurting my eyes and tires me.',
  'Instantly forget what I just saw.',
  'Confuse shape or sound regularly.',
  'Trouble with heavy left confusions.',
  'I can’t remember specifically.',
  'It can get quite complicated.',
  'Bad typesetting can be dreadful.',
  'From my point of view.',
  'Pressured and stressed.',
  'It gets easier with training.',
  'I prefer not to know my audience.',
  'I am not afraid to ask for help.',
  'I don’t read for pleasure.',
  'Switched and swapped letters.',
  'Things in between are quite blurry.',
  'Think twice or get it checked.',
  'Nothing too thin or too bold.',
  'Knowledge is key.',
  'A combination of the two.',
  'It runs in the family.',
  'Focussing on reading out loud.',
  'Learn to live with the disorder.',
  'Practical and straightforward.',
  'It became immediately easier.',
];
