export const generals = [
  {
    type: 'word',
    font: 'sans',
    letterCase: 'lower',
    alignment: 'center',
    background: 'bright',
    weight: 'regular',
    size: 65,
    speed: 50,
    color: 0,
  },
  {
    type: 'word',
    font: 'sans',
    letterCase: 'upper',
    alignment: 'left',
    background: 'bright',
    weight: 'regular',
    size: 100,
    speed: 50,
    color: 0,
  },
  {
    type: 'sentence',
    font: 'sans',
    letterCase: 'lower',
    alignment: 'center',
    background: 'dark',
    weight: 'regular',
    size: 24,
    speed: 50,
    color: '#f90032',
  },
  {
    type: 'word',
    font: 'sans',
    letterCase: 'lower',
    alignment: 'center',
    background: 'bright',
    weight: 'regular',
    size: 65,
    speed: 50,
    color: 0,
  },
];
